# Generated by Django 2.1.7 on 2019-04-05 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=200, verbose_name='属性')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='個数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whose', to=settings.AUTH_USER_MODEL, verbose_name='誰の')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
