# Generated by Django 2.1.7 on 2019-04-06 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, '飲み物'), (2, '食べ物'), (3, 'その他')], default=1, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='個数'),
        ),
    ]
